### PR TITLE
Check for used languages in cyclic module deps

### PR DESCRIPTION
**Pull request by alamqadem**
I noticed that we can have a cyclic dependency also from `Used Languages` and not only from `Module Dependencies`.
For this reason I would like to include `Used Languages` in the check for cyclic module dependencies.

### CODE REVIEW

**Comment by danielratiu** [comment]
looks good in general - I do not understand why this linter "cyclic_module_dependencies" was changed ...

**Comment by ratiud** [comment]
thank you - looks good and I think that we can merge

**Comment by alamqadem** [comment]
> thank you - looks good and I think that we can merge

Trying to run the linters after building, I see that it takes a very very long time.
Do you think what I'm doing there is conceptually correct?

**Comment by danielratiu** [comment]
> > thank you - looks good and I think that we can merge
> 
> Trying to run the linters after building, I see that it takes a very very long time. Do you think what I'm doing there is conceptually correct?

it might be that you find many more cycles ... :-)

**Pull request merged**
